# Site settings
title: DucLe 
description: >
  Duc Le's personal blog about CTF, reverse engineering, security and other random stuff.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duc-le.github.io" # the base hostname & protocol for your site

author:
  fullname: Duc Le
  #googleplus: https://www.google.com/+MotaquillahMaddane
  github: duc-le 
  twitter: _duc_le
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: 'github'
styles: [github]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: rouge
markdown: kramdown

